config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "about_app#index"

  resources :about_app, only: :index
  resources :users, only: [:edit, :update] do
    resources :events, only: [:index, :create, :edit, :update, :destroy] do
      resources :shifts, only: [:index, :create, :edit, :update, :destroy] do
        collection do
          delete :remove_all_shifts
        end
      end
      resources :members, only: [:index, :create, :edit, :update, :destroy] do
        collection do
          post :import
          delete :remove_member_list
          delete :destroy_together
        end
      end
      resources :members_schedules do
        collection do
          get :edit_members_schedules
          delete :destroy_together
        end
      end
      resources :works, only: [:index, :create, :edit, :update, :destroy] do
        collection do
          post :import
          delete :destroy_together
        end
      end
      resources :works_schedules do
        collection do
          get :edit_works_schedules
          delete :destroy_together
        end
      end
    end
  end
end

app/models/shift.rb
class Shift < ApplicationRecord
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :authenticate_user!

  def index
    begin
      @event = Event.find(params[:event_id])
      @schedules = Schedule.preload(:event).where(event_id: @event.id)
      @members = Member.preload(:event).where(event_id: @event.id)
      @works = Work.preload(:event).where(event_id: @event.id)
      @shifts = Shift.where(event_id: @event.id)
    rescue
    end
  end

  def create
    event = Event.find(params[:event_id])
    works = Work.where(event_id: event.id)
    schedules = Schedule.where(event_id: event.id)
    members = Member.where(event_id: event.id).pluck(:id)
    begin
      works.each do |work|
        schedules.each do |schedule|
          if WorksSchedule.exists?(schedule_id: schedule.id, work_id: work.id)
            shift = Shift.new(
              work_id: work.id,
              schedule_id: schedule.id,
              member_id: (members -
                (MembersSchedule.where(schedule_id: schedule.id).pluck(:member_id)) -
                (Shift.where(schedule_id: (schedule.id - 1)).pluck(:member_id)) -
                (Shift.where(schedule_id: (schedule.id + 1)).pluck(:member_id)) -
                (Shift.where(schedule_id: schedule.id).pluck(:member_id))).sort_by{ rand }.first,
              event_id: event.id
            )
            next unless shift.save
          end
        end
      end
      flash[:notice] = "シフトを作成しました。"
      redirect_to user_event_shifts_path(current_user.id, event.id)
    rescue => e
      flash[:notice] = "シフトの作成に失敗しました。#{e.class}"
      redirect_to user_event_shifts_path(current_user.id, event.id)
    end
  end

  def edit
    @event = Event.find(params[:event_id])
    @shift = Shift.find(params[:id])
    @member = Member.find(@shift.member_id)
    @schedule = Schedule.find(@shift.schedule_id)
    @work = Work.find(@shift.work_id)
    @q = @event.members.ransack(params[:q])
    @members = @q.result.pluck(:name)
  end

  def update
    shift = Shift.find(params[:id])
    event = Event.find(params[:event_id])
    member = Member.find_by(name: params[:shift][:member_name])
    if shift.update(member_id: member.id)
      flash[:notice] = "シフトを修正しました"
      redirect_to user_event_shifts_path(current_user.id, event.id)
    else
      flash.now[:alert] = "シフトの編集に失敗しました"
    end
  end

  def remove_all_shifts
    event = Event.find(params[:event_id])
    shifts = Shift.where(event_id: event.id)
    if shifts.destroy_all
      flash[:notice] = "シフトを削除しました"
      redirect_to user_event_shifts_path(current_user.id, event.id)
    else
      flash.now[:alert] = "シフトの削除に失敗しました"
      render action: :index
    end
  end

  def get_member_number

  end
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/shifts/edit.html.erb
<div>
  <%= render partial: "layouts/header" %>
  <aside class="fixed min-w-[184px] w-[184px] h-screen pt-[72px] bg-[#4A5459] z-30" aria-label="Sidebar">
    <div class="overflow-y-auto">
      <%= link_to user_event_shifts_path(current_user.id, @event.id), class: "flex items-center h-12 pl-4 hover:bg-[#6C7275] text-main-white" do %>
        <%= embedded_svg('shift-image', class: "mr-4") %>
        <div>シフト表</div>
      <% end %>
      <button class="flex items-center w-full h-12 pl-4 hover:bg-[#6C7275] text-main-white" type="button" data-modal-toggle="defaultModal">
        <%= embedded_svg('staff-image', class: "mr-4") %>
        スタッフ管理
      </button>
      <button class="flex items-center w-full h-12 pl-4 hover:bg-[#6C7275] text-main-white" type="button" data-modal-toggle="defaultModal">
        <%= embedded_svg('work-image', class: "mr-4") %>
        仕事管理
      </button>
      <%= link_to user_events_path(current_user.id), class: "flex items-center h-12 pl-4 hover:bg-[#6C7275] text-main-white" do %>
        <%= embedded_svg('shop-image', class: "mr-4") %>
        <div>イベント管理</div>
      <% end %>
      <%= link_to "#", class: "flex items-center h-12 pl-4 hover:bg-[#6C7275] text-main-white" do %>
        <%= embedded_svg('human-image', class: "mr-4") %>
        <div>アカウント管理</div>
      <% end %>
    </div>
  </aside>
</div>
<div class="pt-[72px] pl-[184px]">
  <div class="pt-8 mb-10">
    <div class="px-14">
      <%= link_to user_event_shifts_path(current_user.id, @event.id), class: "block mb-8 text-main-blue leading-none" do %>
        <div class="flex gap-x-2 w-fit stroke-main-blue hover:text-main-bluehover hover:stroke-main-bluehover">
          <%= embedded_svg('back-image', class: "") %>
          <div>戻る</div>
        </div>
      <% end %>
      <h1 class="mb-8 text-main-black text-2xl"><%= @work.name %>　<%= @schedule.time_zone %>~　の編集</h1>
      <%= search_form_for @q, url: edit_user_event_shift_path(current_user.id, @event.id) do |f| %>
        <%= render partial: "layouts/search_form", locals: { f: f } %>
      <% end %>
      <div class="mb-8 px-8">
        <%= form_with model: @shift, url: user_event_shift_path(current_user.id, @event.id, @shift.id), data: { turbo: false } do |f| %>
          <div class="flex items-end gap-[88px] mt-12">
            <div class="w-full">
              <%= f.label :member_name, "スタッフの変更(変更前：#{@member.name})", class: "block mb-6 text-xl" %>
              <%= f.select :member_name, @members, { include_blank: "選択する" }, class: "block w-full border border-line-100 rounded-md" %>
            </div>
            <div class="min-w-32">
              <%= f.submit "変更する", class: "block py-2 w-32 h-10 text-center text-main-white bg-main-blue rounded-md main-shadow hover:bg-main-bluehover" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shifts/index.html.erb
<div>
  <%= render partial: "layouts/header" %>
  <aside class="fixed min-w-[184px] w-[184px] h-screen pt-[72px] bg-[#4A5459] z-30" aria-label="Sidebar">
    <div class="overflow-y-auto">
      <%= link_to user_event_shifts_path(current_user.id, @event.id), class: "flex items-center h-12 pl-4 hover:bg-[#6C7275] text-main-white" do %>
        <%= embedded_svg('shift-image', class: "mr-4") %>
        <div>シフト表</div>
      <% end %>
      <% if @shifts.present? %>
        <button class="flex items-center w-full h-12 pl-4 hover:bg-[#6C7275] text-main-white" type="button" data-modal-toggle="defaultModal">
        <%= embedded_svg('staff-image', class: "mr-4") %>
        スタッフ管理
        </button>
        <button class="flex items-center w-full h-12 pl-4 hover:bg-[#6C7275] text-main-white" type="button" data-modal-toggle="defaultModal">
          <%= embedded_svg('work-image', class: "mr-4") %>
          仕事管理
        </button>
      <% else %>
        <%= link_to user_event_members_path(current_user.id, @event.id), class: "flex items-center h-12 pl-4 hover:bg-[#6C7275] text-main-white" do %>
          <%= embedded_svg('staff-image', class: "mr-4") %>
          <div>スタッフ管理</div>
        <% end %>
        <%= link_to user_event_works_path(current_user.id, @event.id), class: "flex items-center h-12 pl-4 hover:bg-[#6C7275] text-main-white" do %>
          <%= embedded_svg('work-image', class: "mr-4") %>
          <div>仕事管理</div>
        <% end %>
      <% end %>
      <%= link_to user_events_path(current_user.id), class: "flex items-center h-12 pl-4 hover:bg-[#6C7275] text-main-white" do %>
        <%= embedded_svg('shop-image', class: "mr-4") %>
        <div>イベント管理</div>
      <% end %>
      <%= link_to "#", class: "flex items-center h-12 pl-4 hover:bg-[#6C7275] text-main-white" do %>
        <%= embedded_svg('human-image', class: "mr-4") %>
        <div>アカウント管理</div>
      <% end %>
    </div>
  </aside>
</div>
<div class="pt-[72px] pl-[184px] pb-[72px]">
  <h1 class="px-14 my-6 text-main-black text-2xl font-bold">シフト表</h1>
  <% if (WorksSchedule.exists?(event_id: @event.id)) && (MembersSchedule.exists?(event_id: @event.id)) && (@shifts.blank?) %>
    <div class="flex flex-col justify-center items-center w-full pt-40">
      <%= embedded_svg('fv-shift-image', class: "") %>
      <%= button_to "シフトを作成", user_event_shifts_path(current_user.id, @event.id), method: :post, class: "block mx-auto mt-12 py-4 text-center w-[400px] h-12 bg-main-blue rounded-md text-white font-bold leading-none main-shadow hover:bg-main-bluehover" %>
    </div>
  <% elsif (WorksSchedule.exists?(event_id: @event.id)) && (MembersSchedule.exists?(event_id: @event.id)) %>
    <div class="flex flex-col gap-16 mt-10 px-14">
      <div class="w-full overflow-x-scroll border">
        <table class="border table-to-export" data-sheet-name="スタッフ軸">
          <tr>
            <th height="32px" class="border-line-100 border-r border-b min-w-[120px]"></th>
            <th height="32px" class="border-line-100 border-r border-b w-20 min-w-[80px]">
              シフト数
            </th>
            <% @schedules.each do |schedule| %>
              <th height="32px" class="bg-[#EBEBEB] border-r border-line-100 border-b leading-none min-w-[140px]">
                <%= schedule.time_zone %>
              </th>
            <% end %>
          </tr>
          <% @members.each do |member| %>
            <tr height="32px" width="140px" align="center" class="text-base font-bold border-b min-w-[140px]">
              <td class="border-r border-line-100 py-1 px-1">
                <div>
                  <%= member.name %>
                </div>
              </td>
              <td class="border-r border-line-100 py-1 px-1">
                <div>
                  <%= Shift.where(event_id: @event.id, member_id: member.id).count %>
                </div>
              </td>
              <% @schedules.each do |schedule| %>
                <% if MembersSchedule.exists?(schedule_id: schedule.id, member_id: member.id) %>
                  <td class="border-r border-line-100 bg-main-red">
                    <div class="text-white font-bold">休み</div>
                  </td>
                <% else %>
                  <% if @shifts.present? %>
                    <% if @shifts.where(schedule_id: schedule.id)&.find_by(member_id: member.id).present? %>
                      <td class="border-r border-line-100">
                        <%= @works.find(@shifts.where(schedule_id: schedule.id).find_by(member_id: member.id).work_id).name %>
                      </td>
                    <% else %>
                      <td class="bg-[#a9a9a9] border-r border-line-100"></td>
                    <% end %>
                  <% else %>
                    <td class="border-r border-line-100"></td>
                  <% end %>
                <% end %>
              <% end %>
            </tr>
          <% end %>
        </table>
      </div>
      <div class="mb-20">
        <div class="w-full overflow-x-scroll border-x">
          <table class="border table-to-export" data-sheet-name="仕事軸">
            <tr>
              <th height="32px" class="border-r border-line-100 border-b min-w-[120px]"></th>
              <th height="32px" class="border-r border-line-100 border-b min-w-[80px]">
                人員
              </th>
              <% @schedules.each do |schedule| %>
                <th width="120px" height="32px" class="bg-[#EBEBEB] border-r border-line-100 border-b leading-none min-w-[72px]">
                  <%= schedule.time_zone %>
                </th>
              <% end %>
            </tr>
            <% @works.each do |work| %>
              <tr height="32px" align="center" class="text-base font-bold border-b min-w-[120px]">
                <td class="border-r border-line-100">
                  <%= work.name %>
                </td>
                <td>
                  <%= Shift.where(event_id: @event.id, work_id: work.id).count %>
                </td>
                <% @schedules.each do |schedule| %>
                  <% if WorksSchedule.exists?(work_id: work.id, schedule_id: schedule.id) %>
                    <td class="border-r border-line-100 min-w-[120px]">
                      <% if @shifts.present? %>
                        <% if @shifts.find_by(schedule_id: schedule.id, work_id: work.id).present? %>
                          <%= link_to edit_user_event_shift_path(current_user.id, @event.id, @shifts.find_by(schedule_id: schedule.id, member_id: @shifts.find_by(schedule_id: schedule.id, work_id: work.id).member_id, work_id: work.id)), class: "text-main-blue hover:underline" do %>
                            <%= Member.find(@shifts.find_by(schedule_id: schedule.id, work_id: work.id).member_id).name %>
                          <% end %>
                        <% else %>
                          <td class="bg-[#a9a9a9] border-r border-line-100"></td>
                        <% end %>
                      <% end %>
                    </td>
                  <% else %>
                    <td class="border-r border-line-100 pb-1 bg-[#a9a9a9] min-w-[120px]"></td>
                  <% end %>
                <% end %>
              </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
    <div class="fixed bottom-0 left-[184px] pr-14 w-full h-[88px] bg-main-white border-t-2 border-line-100 z-20">
      <div class="flex items-center gap-6">
        <%= button_to "シフトを削除する", remove_all_shifts_user_event_shifts_path(current_user.id, @event.id), method: :delete, class: "my-7 mx-16 w-fit text-xl text-[#FF764A] hover:underline" %>
        <button type="button" id="dl-xlsx" class="absolute right-[240px] w-[380px] h-10 text-center bg-accent-logo text-main-white font-bold px-8 py-2 rounded-md cursor-pointer main-shadow hover:bg-main-bluehover">
          シフトをエクセルでダウンロード
        </button>
      </div>
    </div>
  <% elsif (WorksSchedule.exists?(event_id: @event.id)) %>
    <div class="flex flex-col justify-center items-center w-full pt-40">
      <%= embedded_svg('fv-shift-image', class: "") %>
      <p class="mt-3 text-center text-2xl text-main-black leading-10"><span class="text-main-blue">スタッフ管理</span><br>から情報を入力してください</p>
    </div>
  <% elsif (MembersSchedule.exists?(event_id: @event.id)) %>
    <div class="flex flex-col justify-center items-center w-full pt-40">
      <%= embedded_svg('fv-shift-image', class: "") %>
      <p class="mt-3 text-center text-2xl text-main-black leading-10"><span class="text-main-blue">仕事管理</span><br>から情報を入力してください</p>
    </div>
  <% else %>
    <div class="flex flex-col justify-center items-center w-full pt-40">
      <%= embedded_svg('fv-shift-image', class: "") %>
      <p class="mt-3 text-center text-2xl text-main-black leading-10"><span class="text-main-blue"><%= link_to "スタッフ管理", user_event_members_path(current_user.id, @event.id) %>、<%= link_to "仕事管理", user_event_works_path(current_user.id, @event.id) %></span><br>から情報を入力してください</p>
    </div>
  <% end %>
</div>
<!-- Main modal -->
<div id="defaultModal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 w-full md:inset-0 h-modal md:h-full justify-center items-center">
  <div class="relative p-4 w-full max-w-2xl h-full md:h-auto">
    <!-- Modal content -->
    <div class="relative bg-white shadow">
      <!-- Modal header -->
      <div class="p-4">
        <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" data-modal-toggle="defaultModal">
          <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
          </svg>
          <span class="sr-only">Close modal</span>
        </button>
      </div>
      <!-- Modal body -->
      <div class="pt-8 px-6 text-center text-main-black text-2xl leading-10">
        スタッフや仕事の編集を行う場合は、<br>一度シフトを削除してから編集してください
      </div>
      <!-- Modal footer -->
      <div class="flex items-center justify-center py-12">
        <%= button_to "シフトを削除する", remove_all_shifts_user_event_shifts_path(current_user.id, @event.id), method: :delete, class: "block mx-auto py-2 text-center w-[280px] h-10 bg-main-red rounded-md text-white leading-none main-shadow hover:bg-main-redhover" %>
      </div>
    </div>
  </div>
</div>

<script>
  document.getElementById("dl-xlsx").addEventListener(
  "click",
  function () {
    var wopts = {
      bookType: "xlsx",
      bookSST: false,
      type: "binary",
    };

    var workbook = { SheetNames: [], Sheets: {} };

    document
      .querySelectorAll("table.table-to-export")
      .forEach(function (currentValue, index) {
        var n = currentValue.getAttribute("data-sheet-name");
        if (!n) {
          n = "Sheet" + index;
        }
        workbook.SheetNames.push(n);
        workbook.Sheets[n] = XLSX.utils.table_to_sheet(currentValue, wopts);
      });

    var wbout = XLSX.write(workbook, wopts);

    function s2ab(s) {
      var buf = new ArrayBuffer(s.length);
      var view = new Uint8Array(buf);
      for (var i = 0; i != s.length; ++i) {
        view[i] = s.charCodeAt(i) & 0xff;
      }
      return buf;
    }

    saveAs(
      new Blob([s2ab(wbout)], { type: "application/octet-stream" }),
      "Mshift-完成シフト.xlsx"
    );
  },
  false
);

</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.9.10/xlsx.full.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.3/FileSaver.min.js"></script>
<script src="export-xlsx.js"></script>