config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "about_app#index"

  resources :about_app, only: :index
  resources :users, only: [:edit, :update] do
    resources :events, only: [:index, :create, :edit, :update, :destroy] do
      resources :shifts, only: [:index, :create, :edit, :update, :destroy] do
        collection do
          delete :remove_all_shifts
        end
      end
      resources :members, only: [:index, :create, :edit, :update, :destroy] do
        collection do
          post :import
          delete :remove_member_list
          delete :destroy_together
        end
      end
      resources :members_schedules do
        collection do
          get :edit_members_schedules
          delete :destroy_together
        end
      end
      resources :works, only: [:index, :create, :edit, :update, :destroy] do
        collection do
          post :import
          delete :destroy_together
        end
      end
      resources :works_schedules do
        collection do
          get :edit_works_schedules
          delete :destroy_together
        end
      end
    end
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <% case key %>
  <% when "notice" %>
    <div class="fixed top-24 translate-x-1/2 right-6 sm:translate-x-0 z-30 w-fit max-w-[90%] sm:max-w-1/2 py-4 px-6 flex justify-center items-center bg-white shadow-lg border border-line-100 rounded-[3px] animate-flash">
      <div class="my-auto mx-4">
        <%= embedded_svg('check', class: "h-4 fill-dark-blue-200") %>
      </div>
      <p class="text-base font-bold text-dark-blue-200 !leading-none"><%= value %></p>
    </div>
  <% when "alert" %>
    <div class="fixed top-24 translate-x-1/2 right-6 sm:translate-x-0 z-30 w-fit max-w-[90%] sm:max-w-1/2 py-4 px-6 flex justify-center items-center bg-white shadow-lg border border-line-100 rounded-[3px] animate-flash">
      <div class="my-auto mr-4">
        <%= embedded_svg('close', class: "h-4 w-4 fill-secondary-200") %>
      </div>
      <p class="text-base font-bold text-secondary-200"><%= value %></p>
    </div>
  <% else %>
    <p class="alert alert-<%= key %>"><%= value %></p>
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<div class="fixed flex pt-3 pl-6 pr-8 bg-accent-header h-[72px] w-full z-40">
  <h1 class="text-5xl text-white font-bold font-logo tracking-wide leading-none">Mshift</h1>
  <div class="ml-auto"><%= button_to "ログアウト", destroy_user_session_path, method: :delete, class: "w-32 h-12 bg-primary-300 text-center text-white font-bold !leading-none" %></div>
</div>

app/views/layouts/_search_form.html.erb
<div class="flex items-center text-base text-[#989898]">
  <%= embedded_svg('search-image', class: "mr-2") %>
  絞り込み
</div>
<div data-controller="search-form" class="mb-12 w-full">
  <div class="flex items-center justify-evenly gap-8 my-4 p-4 border border-line-100 rounded-md">
    <div class="flex items-center gap-4">
      <%= f.label :name_cont, "氏名", class: "text-main-black" %>
      <%= f.search_field :name_cont, data: { search_form_target: "textForm" }, class: "w-[280px] border border-line-100 rounded-md" %>
    </div>
    <div class="flex items-center gap-4">
      <%= f.label :grade_cont, "学年", class: "text-main-black" %>
      <%= f.select :grade_cont, @event.members.pluck(:grade).uniq, { include_blank: "選択する" }, data: { search_form_target: "selectForm" }, class: "w-[160px] border border-line-100 rounded-md" %>
    </div>
    <div class="flex items-center gap-4">
      <%= f.label :department_cont, "部局", class: "text-main-black" %>
      <%= f.select :department_cont, @event.members.pluck(:department).uniq, { include_blank: "選択する" }, data: { search_form_target: "selectForm" }, class: "w-[200px] border border-line-100 rounded-md" %>
    </div>
    <div class="flex items-center gap-4">
      <%= f.label :position_cont, "担当", class: "text-main-black" %>
      <%= f.search_field :position_cont, data: { search_form_target: "textForm" }, class: "w-[280px] border border-line-100 rounded-md" %>
    </div>
  </div>
  <div class="flex justify-end items-center gap-6 mt-6">
    <button data-action="click->search-form#removeValue" type="button" class="text-main-blue text-sm hover:underline">
      フォームをクリアする
    </button>
    <%= f.submit "検索する", class: "block text-center py-2 w-48 h-10 text-main-white bg-main-blue rounded-md main-shadow hover:bg-main-bluehover" %>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<aside class="fixed min-w-[184px] w-[184px] h-screen pt-[72px] bg-[#4A5459] z-30" aria-label="Sidebar">
  <div class="overflow-y-auto">
    <%= link_to user_event_shifts_path(current_user.id, @event.id), class: "flex items-center h-12 pl-4 hover:bg-[#6C7275] text-main-white" do %>
      <%= embedded_svg('shift-image', class: "mr-4") %>
      <div>シフト表</div>
    <% end %>
    <%= link_to user_event_members_path(current_user.id, @event.id), class: "flex items-center h-12 pl-4 hover:bg-[#6C7275] text-main-white" do %>
      <%= embedded_svg('staff-image', class: "mr-4") %>
      <div>スタッフ管理</div>
    <% end %>
    <%= link_to user_event_works_path(current_user.id, @event.id), class: "flex items-center h-12 pl-4 hover:bg-[#6C7275] text-main-white" do %>
      <%= embedded_svg('work-image', class: "mr-4") %>
      <div>仕事管理</div>
    <% end %>
    <%= link_to user_events_path(current_user.id), class: "flex items-center h-12 pl-4 hover:bg-[#6C7275] text-main-white" do %>
      <%= embedded_svg('shop-image', class: "mr-4") %>
      <div>イベント管理</div>
    <% end %>
    <%= link_to "#", class: "flex items-center h-12 pl-4 hover:bg-[#6C7275] text-main-white" do %>
      <%= embedded_svg('human-image', class: "mr-4") %>
      <div>アカウント管理</div>
    <% end %>
  </div>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mshift</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jomhuria&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400;500;700&display=swap" rel="stylesheet">
  </head>

  <body class="font-body">
    <%= render partial: "layouts/flash" %>
    <%= yield %>
    <%= javascript_include_tag "flowbite", "data-turbo-track": "reload", defer: true %>
  </body>
</html>