config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "about_app#index"

  resources :about_app, only: :index
  resources :users, only: [:edit, :update] do
    resources :events, only: [:index, :create, :edit, :update, :destroy] do
      resources :shifts, only: [:index, :create, :edit, :update, :destroy] do
        collection do
          delete :remove_all_shifts
        end
      end
      resources :members, only: [:index, :create, :edit, :update, :destroy] do
        collection do
          post :import
          delete :remove_member_list
          delete :destroy_together
        end
      end
      resources :members_schedules do
        collection do
          get :edit_members_schedules
          delete :destroy_together
        end
      end
      resources :works, only: [:index, :create, :edit, :update, :destroy] do
        collection do
          post :import
          delete :destroy_together
        end
      end
      resources :works_schedules do
        collection do
          get :edit_works_schedules
          delete :destroy_together
        end
      end
    end
  end
end

app/models/member.rb
class Member < ApplicationRecord

  belongs_to :event

  # validates :grade, inclusion: { in: Member.grades.keys }
  validates :department, presence: true
  validates :position, presence: true
  validates :grade, presence: true
  validates :name, presence: true

  scope :available, -> (event_id, schedule_id) { ((where(event_id: event_id).pluck(:id)) - (MembersSchedule.where(schedule_id: schedule_id).pluck(:member_id)) - (Shift.where(schedule_id: (schedule_id - 1)).pluck(:member_id)) - (Shift.where(schedule_id: (schedule_id + 1)).pluck(:member_id)) - (Shift.where(schedule_id: schedule_id).pluck(:member_id))) }

  def self.import(file, event_id)
    Member.transaction do
      xlsx = Roo::Excelx.new(file.tempfile)
      xlsx.each_row_streaming(offset: 1) do |row|
        member = self.new(department: row[1]&.value, grade: row[2]&.value, name: row[3]&.value, position: row[4]&.value, event_id: event_id)
        next if self.pluck(:id).include?(member.id)
        member.save
      end
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_user!

  def index
    @event = Event.find(params[:event_id])
    @q = Member.where(event_id: @event.id).ransack(params[:q])
    @members = @q.result
    @member = Member.new
    @schedules = Schedule.where(event_id: @event.id)
    if params[:format] == "excel"
      template_file = "public/download_file/Mshift-テンプレ名簿-20xx年度.xlsx"
      send_file template_file
    end
  end

  def import
    event = Event.find(params[:event_id])
    file = params[:file]
    if params[:file].nil?
      file = params[:member][:file]
    else
      file = params[:file]
    end
    accept_format = ".xlsx"
    if File.extname(params[:member][:file].original_filename) == accept_format
      Member.import(file, event.id)
      flash[:notice] = "ファイルをアップロードしました"
      redirect_to user_event_members_path(current_user.id, event.id)
    else
      flash[:alert] = "ファイルのアップロードに失敗しました"
      redirect_to user_event_members_path(current_user.id, event.id)
    end
  end

  def create
    event = Event.find(params[:event_id])
    member = Member.new(member_params(event.id))
    if member.save
      flash[:notice] = "スタッフを追加しました。"
      redirect_to user_event_members_path(current_user.id, event.id)
    else
      flash.now[:alert] = "スタッフの追加に失敗しました"
      render action: :index
    end
  end

  def edit
    @event = Event.find(params[:event_id])
    @member = Member.find(params[:id])
  end

  def update
    @event = Event.find(params[:event_id])
    @member = Member.find(params[:id])
    if @member.update(member_params(@event.id))
      flash[:notice] = "スタッフの編集をしました"
      redirect_to user_event_members_path(current_user.id, @event.id)
    else
      flash.now[:alert] = "スタッフの編集に失敗しました"
      render action: :edit
    end
  end

  def destroy_together
    members = Member.where(event_id: params[:event_id])
    ActiveRecord::Base.transaction do
      members.each do |member|
        member.destroy!
      end
    end
    flash[:notice] = "スタッフを削除しました"
    redirect_to user_event_members_path(current_user.id, params[:event_id])
  end

  private

  def member_params(event_id)
    params.require(:member).permit(:name, :grade, :department, :position).merge(event_id: event_id)
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/edit.html.erb
<div>
  <%= render partial: "layouts/header" %>
  <%= render partial: "layouts/sidebar" %>
</div>
<div class="pt-[72px] pl-[184px] pb-[88px]">
  <div class="px-14 pb-14">
    <%= link_to user_event_members_path(current_user.id, @event.id), class: "block mt-10 text-main-blue leading-none" do %>
      <div class="flex gap-x-2 w-fit stroke-main-blue hover:text-main-bluehover hover:stroke-main-bluehover">
        <%= embedded_svg('back-image', class: "") %>
        <div>戻る</div>
      </div>
    <% end %>
    <h1 class="my-6 text-2xl font-bold"><%= @member.name %>の管理</h1>
    <div class="w-full">
      <%= form_with model: @member, url: user_event_member_path(current_user.id, @event.id, @member.id), method: :patch, data: { turbo: false } do |f| %>
        <div class="mb-6">
          <%= f.label :grade, "学年", class: "block mb-2 text-main-black" %>
          <%= f.text_field :grade, class: "w-full border-line-100 rounded-md placeholder-line-100" %>
        </div>
        <div class="mb-6">
          <%= f.label :name, "氏名", class: "block mb-2 text-main-black" %>
          <%= f.text_field :name, class: "w-full border-line-100 rounded-md placeholder-line-100" %>
        </div>
        <div class="mb-6">
          <%= f.label :department, "部局", class: "block mb-2 text-main-black" %>
          <%= f.text_field :department, class: "w-full border-line-100 rounded-md placeholder-line-100" %>
        </div>
        <div class="mb-8">
          <%= f.label :position, "役職・担当", class: "block mb-2 text-main-black" %>
          <%= f.text_field :position, class: "w-full border-line-100 rounded-md placeholder-line-100" %>
        </div>
        <div class="">
          <%= f.submit "保存する", class: "block text-center ml-auto w-[120px] h-10 bg-accent-logo text-main-white rounded-md main-shadow hover:bg-main-blue cursor-pointer" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="fixed bottom-0 left-[184px] w-full h-[88px] bg-main-white border-t-2 border-line-100 z-20">
    <%= link_to "スタッフを削除する", user_event_member_path(current_user.id, @event.id, @member.id), class: "block my-7 mx-16 w-fit text-xl text-[#FF764A] hover:underline" %>
  </div>
</div>

app/views/members/index.html.erb
<div>
  <div>
    <%= render partial: "layouts/header" %>
    <%= render partial: "layouts/sidebar" %>
  </div>
  <div class="pt-[72px] pl-[184px] pb-[88px]">
    <div class="px-14 pb-14">
      <h1 class="mt-10 mb-8 text-2xl font-bold">スタッフ管理</h1>
      <% if @event.members.present? %>
        <%= search_form_for @q, url: user_event_members_path(current_user.id, @event.id) do |f| %>
          <%= render partial: "layouts/search_form", locals: { f: f } %>
        <% end %>
        <div class="w-full overflow-y-scroll h-[400px]">
          <table class="w-full border-y-2">
            <tr height="48px" class="">
              <th class="w-[36%] bg-[#EBEBEB] border-b-2 leading-none min-w-[120px]">
                氏名
              </th>
              <th class="w-[18%] bg-[#EBEBEB] border-b-2 leading-none min-w-[120px]">
                学年
              </th>
              <th class="w-[18%] bg-[#EBEBEB] border-b-2 leading-none min-w-[120px]">
                部局
              </th>
              <th class="w-[18%] bg-[#EBEBEB] border-b-2 leading-none min-w-[120px]">
                役職・担当
              </th>
              <th class="w-[10%] bg-[#EBEBEB] border-b-2 leading-none min-w-[120px]"></th>
            </tr>
            <% @members.each do |member| %>
              <tr height="64px" align="center" class="w-full text-base font-bold text-main-black border-b-2">
                <td class="">
                  <%= member.name %>
                </td>
                <td>
                  <%= member.grade %>
                </td>
                <td>
                  <%= member.department %>
                </td>
                <td>
                  <%= member.position %>
                </td>
                <td>
                  <%= link_to "編集", edit_user_event_member_path(current_user.id, @event.id, member.id), class: "text-main-blue hover:underline" %>
                </td>
              </tr>
            <% end %>
          </table>
        </div>
      <% else %>
        <div class="flex flex-col justify-center items-center w-full pt-10">
          <%= embedded_svg('fv-work-member-image', class: "") %>
          <p class="mt-3 text-2xl text-main-black">スタッフを追加してください</p>
        </div>
      <% end %>
      <div class="fixed bottom-0 left-[184px] w-full h-[88px] bg-main-white border-t-2 border-line-100 z-20">
        <!-- Modal toggle -->
        <div class="flex gap-8">
          <button class="block ml-14 py-8 text-xl text-main-blue leading-none hover:underline" type="button" data-modal-toggle="defaultModal">
            スタッフを追加する
          </button>
          <%= button_to "スタッフをまとめて削除", destroy_together_user_event_members_path(current_user.id, @event.id), method: :delete, class: "block ml-14 py-8 text-xl text-main-red leading-none hover:underline" %>
        </div>
        <%= link_to "スタッフのシフトを設定する", user_event_members_schedules_path(current_user.id, @event.id), class: "absolute right-[296px] bottom-[22px] py-2 px-4 h-10 w-[240px] text-main-white bg-main-blue rounded-md main-shadow hover:bg-main-bluehover" %>
      </div>
    </div>
  </div>
</div>

<!-- Main modal -->
<div id="defaultModal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 w-full md:inset-0 h-modal md:h-full justify-center items-center">
  <div class="relative p-4 w-full max-w-2xl h-full md:h-auto">
    <!-- Modal content -->
    <div class="relative bg-white shadow">
      <!-- Modal header -->
      <div class="py-2 mb-8 border-b">
        <button type="button" class="absolute left-8 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" data-modal-toggle="defaultModal">
          <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
          </svg>
          <span class="sr-only">Close modal</span>
        </button>
        <div class="text-center text-main-black text-xl">スタッフを追加する</div>
      </div>
      <!-- Modal body -->
      <div class="px-10">
        <div class="w-full border-b-2 border-t-2 border-line-100">
          <ul class="flex justify-center w-full text-sm font-medium text-center" id="myTab" data-tabs-toggle="#myTabContent" role="tablist">
            <li class="mr-2 w-1/2 border-r border-line-100" role="presentation">
              <button class="inline-block p-4 rounded-t-lg border-b-2" id="profile-tab" data-tabs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="false">エクセルで追加</button>
            </li>
            <li class="mr-2 w-1/2" role="presentation">
              <button class="inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300" id="dashboard-tab" data-tabs-target="#dashboard" type="button" role="tab" aria-controls="dashboard" aria-selected="false">手動で追加</button>
            </li>
          </ul>
        </div>
      </div>
      <div id="myTabContent">
        <div
          data-controller="file-form"
          id="profile"
          role="tabpanel"
          aria-labelledby="profile-tab"
          class="hidden p-10 bg-gray-50 rounded-lg"
        >
          <div class="mb-10 pb-10 border-b-2 border-line-100">
            <%= link_to "名簿のテンプレートをダウンロード", user_event_members_path(current_user.id, @event.id, "excel"), class: "block text-center px-2 py-2 w-full h-12 border-2 border-[#0ED18A] text-lg text-[#0ED18A] font-bold rounded-md main-shadow hover:text-[#6BEBBC] hover:border-[#6BEBBC]" %>
          </div>
          <%= form_with model: @member, url: import_user_event_members_path(current_user.id, @event.id), data: { turbo: false } do |f| %>
            <div class="">
              <%= f.label :file, "名簿のファイルのアップロード(.xslxの拡張子で)", class: "block text-center mb-6 px-2 py-2 w-full h-12 border-2 border-accent-logo text-lg text-accent-logo font-bold rounded-md main-shadow hover:text-main-bluehover hover:border-main-bluehover" %>
              <%= f.file_field :file, data: { action: "change->file-form#realize", target: "input" }, class: "hidden" %>
              <div data-file-form-target="fileName" class="text-center text-main-black"></div>
            </div>
            <%= f.submit "登録する", class: "block ml-auto mt-8 h-10 w-32 text-center text-white font-bold bg-main-blue rounded-md main-shadow hover:bg-main-bluehover" %>
          <% end %>
        </div>
        <div
          id="dashboard"
          role="tabpanel"
          aria-labelledby="dashboard-tab"
          class="hidden p-4 rounded-lg"
        >
          <% if @members.present? %>
            <%= form_with model: @member, url: user_event_members_path(current_user.id, @event.id), data: { turbo: false } do |f| %>
              <div class="p-8">
                <div class="mb-6">
                  <%= f.label :name, "氏名", class: "block mb-2 text-main-black" %>
                  <%= f.text_field :name, class: "w-full border-line-100 rounded-md placeholder-line-100" %>
                </div>
                <div class="flex gap-6 mb-6 w-full">
                  <div class="w-1/2">
                    <%= f.label :grade, "学年", class: "block mb-2 text-main-black" %>
                    <%= f.select :grade, @members.pluck(:grade).uniq, {}, class: "w-full rounded-md border-line-100 border" %>
                  </div>
                  <div class="w-1/2">
                    <%= f.label :department, "部局", class: "block mb-2 text-main-black" %>
                    <%= f.select :department, @members.pluck(:department).uniq, {}, class: "w-full border-line-100 rounded-md placeholder-line-100" %>
                  </div>
                </div>
                <div class="">
                  <%= f.label :position, "役職・担当", class: "block mb-2 text-main-black" %>
                  <%= f.text_field :position, class: "w-full border-line-100 rounded-md placeholder-line-100" %>
                </div>
              </div>
              <!-- Modal footer -->
              <div class="flex items-center pr-10 pb-6">
                <%= f.submit "追加する", class: "block text-center ml-auto w-[120px] h-8 bg-accent-logo text-main-white rounded-md main-shadow hover:bg-main-blue" %>
              </div>
            <% end %>
          <% else %>
            <p class="mt-8 mb-20 text-center text-lg text-[#BCBBBB]">先に「エクセルから追加」からスタッフを追加してください</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>